language: php

services:
    - mysql
    - postgresql

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - addons:
          postgresql: "9.4"
        - addons:
          postgresql: "10"

sudo: false

before_script:
    - composer update ${COMPOSER_FLAGS} --no-interaction
    - mysql -e 'DROP DATABASE IF EXISTS phoenix;'
    - mysql -e 'CREATE DATABASE phoenix;'
    - psql -c 'DROP DATABASE IF EXISTS phoenix;' -U postgres
    - psql -c 'CREATE DATABASE phoenix;' -U postgres

script:
    - mkdir -p build/logs
    - composer outdated -D --strict --ignore symfony/console --ignore symfony/finder --ignore symfony/yaml
    - composer require squizlabs/php_codesniffer --dev
    - vendor/bin/phpcs src --standard=PSR2 -n
    - composer remove squizlabs/php_codesniffer --dev
    - composer require phpstan/phpstan --dev
    - vendor/bin/phpstan analyze src --level=5 --no-progress
    - composer remove phpstan/phpstan --dev
    - composer require efabrica/php-extensions-finder --dev
    - vendor/bin/php-extensions-finder check src tests
    - composer remove efabrica/php-extensions-finder --dev
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
