name: PHP static analysis

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]

    name: PHPStan PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer update
        run: composer update

      - name: Install PHPStan as dev dependency
        run: composer require phpstan/phpstan --dev

      - name: PHPStan analyse
        run: vendor/bin/phpstan analyze src --level=5 --no-progress
