name: PHP syntax checker

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0' ]

    name: PHP syntax checker PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check syntax
        run: php -l src tests
